<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>BRZE-Hero-Effect-Duration-Probe-V2</AssemblyName>
    <RootNamespace>BRZEHeroEffectDurationProbeV2</RootNamespace>
  </PropertyGroup>
</Project>
