<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
    <AssemblyName>BRZE-Hero-Effect-Replay-Duration-V11</AssemblyName>
    <RootNamespace>BRZEHeroEffectReplayDurationV11</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="ConfigurableDurationCore.cs" />
    <Compile Include="..\HeroEffectReplayV2\ReplayCore.cs" Link="ReplayCoreV2.cs" />
  </ItemGroup>
</Project>
